#
# Copyright(c) 2020-2023 Liu Hongyu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devbox
      MYSQL_PASSWORD: devbox
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/mysql_db.cnf:/etc/mysql/conf.d/mysql_db.cnf
  redis:
    container_name: redis
    image: redis:4-alpine
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
